from __future__ import annotations

import importlib
import importlib.util
import json
import os
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Protocol

from .config import DEFAULT_EMBEDDING_SETTINGS, SearchSettings
from .models import SearchHit
from .storage import BookRecallStore


class LocalModelError(RuntimeError):
    """Raised when an optional local model dependency or index is unavailable."""


class Embedder(Protocol):
    model_name: str

    def encode(self, texts: list[str], batch_size: int = 64) -> list[list[float]]:
        ...


@dataclass(slots=True)
class VectorIndexInfo:
    book_id: str
    model_name: str
    backend: str
    chunk_count: int
    dimension: int
    path: str


def dependency_report() -> dict[str, object]:
    return {
        "numpy": importlib.util.find_spec("numpy") is not None,
        "sentence_transformers": importlib.util.find_spec("sentence_transformers") is not None,
        "torch": importlib.util.find_spec("torch") is not None,
        "faiss": importlib.util.find_spec("faiss") is not None,
        "recommended_embedding_model": DEFAULT_EMBEDDING_SETTINGS.model_name,
    }


def default_vector_dir(db_path: str) -> Path:
    db = Path(db_path)
    return db.parent / DEFAULT_EMBEDDING_SETTINGS.vector_dir_name


def default_cache_root(db_path: str | Path) -> Path:
    db = Path(db_path).resolve()
    if db.parent.name == ".bookrecall":
        return db.parent.parent / ".cache"
    return db.parent / ".cache"


def default_sentence_transformers_cache_dir(db_path: str | Path) -> Path:
    return default_cache_root(db_path) / "huggingface" / "sentence-transformers"


def configure_local_model_cache(cache_root: str | Path) -> dict[str, str]:
    root = Path(cache_root)
    hf_home = root / "huggingface"
    st_home = hf_home / "sentence-transformers"
    torch_home = root / "torch"

    st_home.mkdir(parents=True, exist_ok=True)
    torch_home.mkdir(parents=True, exist_ok=True)

    os.environ.setdefault("HF_HOME", str(hf_home))
    os.environ.setdefault("SENTENCE_TRANSFORMERS_HOME", str(st_home))
    os.environ.setdefault("TORCH_HOME", str(torch_home))
    os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")

    return {
        "HF_HOME": os.environ["HF_HOME"],
        "SENTENCE_TRANSFORMERS_HOME": os.environ["SENTENCE_TRANSFORMERS_HOME"],
        "TORCH_HOME": os.environ["TORCH_HOME"],
    }


def safe_book_id(book_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", book_id).strip("_") or "book"


def vector_index_paths(index_dir: str | Path, book_id: str) -> tuple[Path, Path]:
    root = Path(index_dir)
    stem = safe_book_id(book_id)
    return root / f"{stem}.npz", root / f"{stem}.json"


def faiss_index_paths(index_dir: str | Path, book_id: str) -> tuple[Path, Path, Path]:
    root = Path(index_dir)
    stem = safe_book_id(book_id)
    return root / f"{stem}.faiss", root / f"{stem}.chunks.json", root / f"{stem}.json"


def delete_vector_index(index_dir: str | Path, book_id: str) -> dict[str, object]:
    """Delete known vector index files for one book.

    Only files generated by ``vector_index_paths`` / ``faiss_index_paths`` are
    targeted.  This keeps the operation scoped to BookRecall's vector folder.
    """
    root = Path(index_dir).resolve()
    candidates = [*vector_index_paths(root, book_id), *faiss_index_paths(root, book_id)]
    deleted: list[str] = []
    for candidate in candidates:
        resolved = candidate.resolve()
        if root not in resolved.parents:
            raise LocalModelError("向量索引路径越界，已拒绝删除。")
        if resolved.exists() and resolved.is_file():
            resolved.unlink()
            deleted.append(str(resolved))
    return {
        "book_id": book_id,
        "deleted_count": len(deleted),
        "deleted_paths": deleted,
    }


class SentenceTransformerEmbedder:
    def __init__(
        self,
        model_name: str = DEFAULT_EMBEDDING_SETTINGS.model_name,
        *,
        cache_dir: str | Path | None = None,
    ) -> None:
        if importlib.util.find_spec("sentence_transformers") is None:
            raise LocalModelError(
                "缺少 sentence-transformers，无法加载本地 embedding 模型。"
                "请先按项目文档安装可选依赖后再运行 embed-build。"
            )
        from sentence_transformers import SentenceTransformer

        self.model_name = model_name
        self.cache_dir = Path(cache_dir) if cache_dir is not None else None
        if self.cache_dir is not None:
            self.cache_dir.mkdir(parents=True, exist_ok=True)
        self._model = SentenceTransformer(
            model_name,
            cache_folder=str(self.cache_dir) if self.cache_dir is not None else None,
        )

    def encode(self, texts: list[str], batch_size: int = 64) -> list[list[float]]:
        vectors = self._model.encode(
            texts,
            batch_size=batch_size,
            normalize_embeddings=True,
            show_progress_bar=False,
        )
        return vectors.tolist()


def _require_numpy():
    if importlib.util.find_spec("numpy") is None:
        raise LocalModelError("缺少 numpy，无法构建或读取本地向量索引。")
    import numpy as np

    return np


def _load_faiss_module() -> Any | None:
    spec = importlib.util.find_spec("faiss")
    if spec is None:
        return None
    return importlib.import_module("faiss")


def _normalize_rows(vectors):
    np = _require_numpy()
    array = np.asarray(vectors, dtype=np.float32)
    if array.ndim != 2:
        raise LocalModelError("embedding 输出必须是二维向量。")
    norms = np.linalg.norm(array, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return array / norms


def build_embedding_index(
    *,
    store: BookRecallStore,
    book_id: str,
    index_dir: str | Path,
    embedder: Embedder,
    batch_size: int = DEFAULT_EMBEDDING_SETTINGS.batch_size,
    limit_chunks: int | None = None,
    prefer_backend: str = "auto",
    faiss_module: Any | None = None,
) -> VectorIndexInfo:
    np = _require_numpy()
    rows = store.iter_search_rows(book_id, max_chapter=None)
    if limit_chunks is not None:
        rows = rows[:limit_chunks]
    if not rows:
        raise LocalModelError(f"book_id={book_id} 没有 child chunk，无法构建向量索引。")

    chunk_ids = [str(row["chunk_id"]) for row in rows]
    texts = [str(row["text"]) for row in rows]

    vectors: list[list[float]] = []
    for start in range(0, len(texts), batch_size):
        batch = texts[start : start + batch_size]
        vectors.extend(embedder.encode(batch, batch_size=batch_size))
    matrix = _normalize_rows(vectors)

    backend = _resolve_backend(prefer_backend, faiss_module)
    if backend == "faiss":
        return _build_faiss_index(
            book_id=book_id,
            index_dir=index_dir,
            embedder=embedder,
            chunk_ids=chunk_ids,
            matrix=matrix,
            faiss_module=faiss_module or _load_faiss_module(),
        )
    return _build_numpy_index(
        book_id=book_id,
        index_dir=index_dir,
        embedder=embedder,
        chunk_ids=chunk_ids,
        matrix=matrix,
        np=np,
    )


def _resolve_backend(prefer_backend: str, faiss_module: Any | None) -> str:
    normalized = (prefer_backend or "auto").strip().lower()
    if normalized not in {"auto", "numpy", "faiss"}:
        raise LocalModelError("未知向量后端，请选择 auto、numpy 或 faiss。")
    if normalized == "numpy":
        return "numpy"
    available_faiss = faiss_module is not None or _load_faiss_module() is not None
    if normalized == "faiss":
        if not available_faiss:
            raise LocalModelError("指定了 faiss 后端，但当前环境没有安装 faiss。")
        return "faiss"
    return "faiss" if available_faiss else "numpy"


def _build_numpy_index(
    *,
    book_id: str,
    index_dir: str | Path,
    embedder: Embedder,
    chunk_ids: list[str],
    matrix,
    np,
) -> VectorIndexInfo:
    index_path, meta_path = vector_index_paths(index_dir, book_id)
    index_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(index_path, chunk_ids=np.asarray(chunk_ids), vectors=matrix)

    info = VectorIndexInfo(
        book_id=book_id,
        model_name=embedder.model_name,
        backend="numpy",
        chunk_count=len(chunk_ids),
        dimension=int(matrix.shape[1]),
        path=str(index_path),
    )
    meta_path.write_text(json.dumps(asdict(info), ensure_ascii=False, indent=2), encoding="utf-8")
    return info


def _build_faiss_index(
    *,
    book_id: str,
    index_dir: str | Path,
    embedder: Embedder,
    chunk_ids: list[str],
    matrix,
    faiss_module: Any | None,
) -> VectorIndexInfo:
    if faiss_module is None:
        raise LocalModelError("当前环境没有可用的 faiss 模块。")
    index_path, chunk_meta_path, meta_path = faiss_index_paths(index_dir, book_id)
    index_path.parent.mkdir(parents=True, exist_ok=True)

    index = faiss_module.IndexFlatIP(int(matrix.shape[1]))
    index.add(matrix)
    faiss_module.write_index(index, str(index_path))
    chunk_meta_path.write_text(json.dumps(chunk_ids, ensure_ascii=False, indent=2), encoding="utf-8")

    info = VectorIndexInfo(
        book_id=book_id,
        model_name=embedder.model_name,
        backend="faiss",
        chunk_count=len(chunk_ids),
        dimension=int(matrix.shape[1]),
        path=str(index_path),
    )
    meta_path.write_text(json.dumps(asdict(info), ensure_ascii=False, indent=2), encoding="utf-8")
    return info


def get_vector_index_info(index_dir: str | Path, book_id: str) -> VectorIndexInfo | None:
    _, meta_path = vector_index_paths(index_dir, book_id)
    _, _, faiss_meta_path = faiss_index_paths(index_dir, book_id)
    for candidate in (meta_path, faiss_meta_path):
        if candidate.exists():
            raw = json.loads(candidate.read_text(encoding="utf-8"))
            return VectorIndexInfo(
                book_id=str(raw["book_id"]),
                model_name=str(raw["model_name"]),
                backend=str(raw.get("backend") or "numpy"),
                chunk_count=int(raw["chunk_count"]),
                dimension=int(raw["dimension"]),
                path=str(raw["path"]),
            )
    return None


class EmbeddingRetriever:
    def __init__(
        self,
        store: BookRecallStore,
        settings: SearchSettings,
        *,
        index_dir: str | Path,
        embedder: Embedder,
        faiss_module: Any | None = None,
    ) -> None:
        self.store = store
        self.settings = settings
        self.index_dir = Path(index_dir)
        self.embedder = embedder
        self.faiss_module = faiss_module
        self._loaded: dict[str, tuple[str, Any, list[str]]] = {}

    def _load(self, book_id: str) -> tuple[str, Any, list[str]]:
        if book_id in self._loaded:
            return self._loaded[book_id]
        info = get_vector_index_info(self.index_dir, book_id)
        if info is None:
            raise LocalModelError(f"book_id={book_id} 还没有向量索引，请先运行 embed-build。")
        if info.backend == "faiss":
            loaded = self._load_faiss_index(book_id)
        else:
            loaded = self._load_numpy_index(book_id)
        self._loaded[book_id] = loaded
        return loaded

    def _load_numpy_index(self, book_id: str) -> tuple[str, Any, list[str]]:
        np = _require_numpy()
        index_path, _ = vector_index_paths(self.index_dir, book_id)
        data = np.load(index_path, allow_pickle=False)
        vectors = data["vectors"].astype(np.float32)
        chunk_ids = [str(item) for item in data["chunk_ids"].tolist()]
        return "numpy", vectors, chunk_ids

    def _load_faiss_index(self, book_id: str) -> tuple[str, Any, list[str]]:
        faiss_module = self.faiss_module or _load_faiss_module()
        if faiss_module is None:
            raise LocalModelError("检测到 faiss 索引，但当前环境无法加载 faiss。")
        index_path, chunk_meta_path, _ = faiss_index_paths(self.index_dir, book_id)
        chunk_ids = json.loads(chunk_meta_path.read_text(encoding="utf-8"))
        index = faiss_module.read_index(str(index_path))
        return "faiss", index, [str(item) for item in chunk_ids]

    def search(self, book_id: str, query: str, max_chapter: int | None = None) -> list[SearchHit]:
        np = _require_numpy()
        backend, index_data, chunk_ids = self._load(book_id)
        query_vector = _normalize_rows(self.embedder.encode([query], batch_size=1))[0]
        scores, candidate_indices = self._search_candidates(backend, index_data, query_vector, np=np)

        rows = self.store.iter_search_rows(book_id, max_chapter=None)
        rows_by_id = {str(row["chunk_id"]): row for row in rows}
        hits: list[SearchHit] = []
        for score, index in zip(scores, candidate_indices):
            if index < 0 or index >= len(chunk_ids):
                continue
            row = rows_by_id.get(chunk_ids[index])
            if row is None:
                continue
            chapter_number = int(row["chapter_number"])
            if max_chapter is not None and chapter_number > max_chapter:
                continue
            hits.append(
                SearchHit(
                    score=float(score),
                    chapter_number=chapter_number,
                    chapter_title=str(row["chapter_title"]),
                    parent_id=str(row["parent_id"]),
                    child_text=str(row["text"]),
                    parent_text=str(row["parent_text"]),
                )
            )

        parent_best: dict[str, SearchHit] = {}
        for hit in hits:
            existing = parent_best.get(hit.parent_id)
            if existing is None or hit.score > existing.score:
                parent_best[hit.parent_id] = hit
        return sorted(parent_best.values(), key=lambda item: (-item.score, item.chapter_number))[
            : self.settings.top_k_parents
        ]

    def _search_candidates(self, backend: str, index_data: Any, query_vector, *, np) -> tuple[list[float], list[int]]:
        candidate_count = max(self.settings.top_k_children * 8, self.settings.top_k_parents * 12, 32)
        if backend == "faiss":
            search_count = min(candidate_count, getattr(index_data, "ntotal", candidate_count))
            scores, indices = index_data.search(query_vector.reshape(1, -1), search_count)
            return scores[0].tolist(), [int(i) for i in indices[0].tolist()]

        vectors = index_data
        scores = vectors @ query_vector
        if scores.size == 0:
            return [], []
        candidate_count = min(scores.size, candidate_count)
        if candidate_count < scores.size:
            selected = np.argpartition(scores, -candidate_count)[-candidate_count:]
            ordered = selected[np.argsort(scores[selected])[::-1]]
        else:
            ordered = np.argsort(scores)[::-1]
        return [float(scores[int(i)]) for i in ordered.tolist()], [int(i) for i in ordered.tolist()]
